# Generated by Django 4.1.2 on 2022-11-03 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Faqat O'zbekiston raqamlari kiriting", regex='^998[0-9]{2}[0-9]{7}$')]),
        ),
    ]
