# Generated by Django 4.1.2 on 2023-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('device_token', models.CharField(max_length=300)),
                ('device_type', models.CharField(blank=True, choices=[('android', 'android'), ('ios', 'ios'), ('other', 'other')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_token',
        ),
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(to='users.device'),
        ),
    ]
