# Generated by Django 4.1.2 on 2022-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delete_likes'),
        ('users', '0004_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(related_name='favourite_order', to='orders.order'),
        ),
    ]
