# Generated by Django 4.1.2 on 2022-11-29 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, help_text='Phone number must be entered in the format: 9989XXXXXXXX', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Faqat O'zbekiston raqamlari kiriting", regex='^998[0-9]{2}[0-9]{7}$')], verbose_name='phone number2'),
        ),
    ]
