# Generated by Django 4.1.2 on 2022-12-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Buyurtma nomi(kiritlishi shart emas), ixtiyoriy.', max_length=50, null=True, verbose_name='name')),
                ('phone2', models.CharField(blank=True, help_text="Faqat o'zbek raqamlari", max_length=13, null=True, verbose_name='phone number2')),
                ('car', models.CharField(blank=True, help_text='Mashina nomi, M: Gentra', max_length=50, null=True, verbose_name='car')),
                ('car_number', models.CharField(blank=True, help_text='Mashina raqami(shart emas), ixtiyoriy', max_length=50, null=True, verbose_name='car_number')),
                ('description', models.TextField(blank=True, help_text="Buyurtma haqida qo'shimcha izoh", null=True, verbose_name='description')),
                ('from_place', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm')], help_text='Joy nomi, qayerdan...', max_length=100, verbose_name='From Place')),
                ('date', models.DateField(blank=True, help_text='Buyurtma vaqti(ketish vaqti) YYYY-MM-DD HH:MM. M: 2022-12-25 09:00', null=True, verbose_name='date')),
                ('time', models.TimeField(blank=True, help_text='Soat: HH:MM:SS, 09:00:00', null=True, verbose_name='time')),
                ('price', models.IntegerField(blank=True, help_text='Narxi', null=True, verbose_name='price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_driver', models.BooleanField(default=False, help_text="Buyurtmani beruvchi shaxs haydovchi bo'lsa True, aks holda False")),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False, help_text='Status: qabul qilinganmi')),
                ('is_finished', models.BooleanField(default=False, help_text='Status: bajarilganmi')),
                ('is_canceled', models.BooleanField(default=False, help_text='Status: rad etilganmi')),
                ('is_paid', models.BooleanField(default=False, help_text="Status: to'langanmi")),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm')], help_text='Viloyat nomi, 14ta tanlov bor.', max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, help_text='Tuman nomi. M: Yunusobod', max_length=50, null=True, verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Buyurtirilgan mashina rasmi', upload_to='orders/%Y/%m/%d/')),
                ('order', models.ForeignKey(help_text='Buyurtma raqami(id)', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Image',
                'verbose_name_plural': 'Order Images',
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Comment',
                'verbose_name_plural': 'Order Comments',
            },
        ),
    ]
