# Generated by Django 4.1.2 on 2022-11-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_from_place_alter_order_to_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
    ]
