# Generated by Django 4.0.3 on 2022-11-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_image_orderimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFile',
        ),
    ]
