# Generated by Django 4.1.2 on 2022-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_forward_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='passengers',
            field=models.ManyToManyField(blank=True, help_text="Yo'lovchilar to'plami", related_name='order_passengers', to='orders.seats'),
        ),
    ]
