# Generated by Django 4.1.2 on 2022-11-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(help_text='Buyurtma raqami(id)', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.order'),
        ),
    ]
