# Generated by Django 4.1.2 on 2022-11-18 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='order_favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
