# Generated by Django 4.1.2 on 2022-11-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='order',
        ),
        migrations.AddField(
            model_name='likes',
            name='order',
            field=models.ManyToManyField(related_name='favourite_order', to='orders.order'),
        ),
    ]
