# Generated by Django 4.1.2 on 2022-11-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_favourite_remove_likes_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
