# Generated by Django 4.1.2 on 2022-11-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='to_place',
            field=models.ForeignKey(help_text='Joy nomi, qayerga...', on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='orders.place'),
        ),
    ]
