# Generated by Django 4.1.2 on 2022-11-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_place_name_place_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(blank=True, help_text='Phone number must be entered in the format', max_length=13, null=True, verbose_name='phone number2'),
        ),
    ]
