# Generated by Django 4.1.2 on 2022-11-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_driver',
            field=models.BooleanField(default=False, help_text="Buyurtmani beruvchi shaxs haydovchi bo'lsa True, aks holda False"),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone2',
            field=models.CharField(blank=True, help_text="Faqat o'zbek raqamlari", max_length=13, null=True, verbose_name='phone number2'),
        ),
    ]
