# Generated by Django 4.1.2 on 2022-12-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_is_driver_alter_order_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, help_text='Buyurtma vaqti(ketish vaqti) YYYY-MM-DD. M: 2022-12-25', null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, help_text='Tuman nomi. M: Yunusobod', max_length=50, null=True, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ("Farg'ona", "Farg'ona"), ('Jizzax', 'Jizzax'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ("Qoraqalpog'iston Respublikasi", "Qoraqalpog'iston Respublikasi"), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Toshkent vil', 'Toshkent vil'), ('Xorazm', 'Xorazm')], help_text='Viloyat nomi, 14ta tanlov bor.', max_length=100, verbose_name='Viloyat'),
        ),
    ]
