# Generated by Django 4.1.2 on 2022-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, help_text='Soat: HH:MM:SS, 09:00:00', null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, help_text='Buyurtma vaqti(ketish vaqti) YYYY-MM-DD HH:MM. M: 2022-12-25 09:00', null=True, verbose_name='date'),
        ),
    ]
