# Generated by Django 4.1.2 on 2022-12-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_forward_free_alter_order_left_back_free_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='forward_free',
            new_name='forward_set',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='left_back_free',
            new_name='left_back_set',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='middle_free',
            new_name='middle_set',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='right_back_free',
            new_name='right_back_set',
        ),
    ]
