# Generated by Django 4.1.2 on 2022-12-16 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0029_rename_forward_free_order_forward_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='forward_set',
        ),
        migrations.RemoveField(
            model_name='order',
            name='left_back_set',
        ),
        migrations.RemoveField(
            model_name='order',
            name='middle_set',
        ),
        migrations.RemoveField(
            model_name='order',
            name='right_back_set',
        ),
        migrations.AddField(
            model_name='order',
            name='forward_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwardseat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='left_back_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftbackseat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='middle_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='middleseat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='right_back_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rightbackseat', to=settings.AUTH_USER_MODEL),
        ),
    ]
